---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-app
  namespace: hypermine-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-app
  template:
    metadata:
      labels:
        app: vault-app
    spec:
      containers:
        - name: vault-app
          image: __GOOGLE_ARTIFACT_URL__/__GOOGLE_PROJECT_ID__/__GOOGLE_ARTIFACT_REPO__/vault-service:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: __PORT__
          livenessProbe:
            httpGet:
              path: /api
              port: __PORT__
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: HOST
              value: __HOST__
            - name: SSL
              value: "__SSL__"
            - name: ABSOLUTE_URL
              value: __ABSOLUTE_URL__
            - name: DATA_VAULT
              value: __DATA_VAULT__
            - name: DB_URL
              value: "__DB_URL__"
            - name: PORT
              value: "__PORT__"
            - name: LOG_LEVEL
              value: "__LOG_LEVEL__"

---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: hypermine-development
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: vault-app
  ports:
    - port: __PORT__
      targetPort: __PORT__
      protocol: TCP
---

