---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-app
  namespace: hypermine-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-app
  template:
    metadata:
      labels:
        app: vault-app
    spec:
      containers:
        - name: vault-app
          image: #{GOOGLE_ARTIFACT_URL}#/#{GOOGLE_PROJECT_ID}#/#{GOOGLE_ARTIFACT_REPO}#/vault-service:latest

          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: HOST
              value: #{HOST}#
            - name: SSL
              value: #{SSL}#
            - name: ABSOLUTE_URL
              value: #{ABSOLUTE_URL}#
            - name: DATA_VAULT
              value: #{DATA_VAULT}#
            - name: DB_URL
              value: #{DB_URL}#
            - name: PORT
              value: "#{PORT}#"
            - name: LOG
              value: #{LOG}#

---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: hypermine-development
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

spec:
  type: NodePort
  selector:
    app: vault-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---

