name: Vault Service Build and Publish to google artifact repository

on:
  push:
    branches:
      - "master"

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: install gcloud cli tools
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{secrets.GOOGLE_PROJECT_ID}}
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true
      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker Auth"
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: "Docker Build and Push"
        env:
          GOOGLE_PROJECT_ID: ${{secrets.GOOGLE_PROJECT_ID}}
          GOOGLE_ARTIFACT_URL: ${{secrets.GOOGLE_ARTIFACT_URL}}
          GOOGLE_ARTIFACT_REPO: ${{secrets.GOOGLE_ARTIFACT_REPO}}
        run:
          docker build -t $GOOGLE_ARTIFACT_URL/$GOOGLE_PROJECT_ID/$GOOGLE_ARTIFACT_REPO/vault-service:latest .

          docker push $GOOGLE_ARTIFACT_URL/$GOOGLE_PROJECT_ID/$GOOGLE_ARTIFACT_REPO/vault-service:latest

  Deploy:
    needs: [Build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: install gcloud cli tools
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{secrets.GOOGLE_PROJECT_ID}}
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true
      - name: "Configure kubectl"
        run: gcloud container clusters get-credentials hypermine-gke --region=asia-south1
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__PORT__/${{ secrets.PORT }}/g'' {} \;
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__HOST__/${{ secrets.HOST }}/g'' {} \;
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__ABSOLUTE_URL__/${{ secrets.ABSOLUTE_URL }}/g'' {} \;
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__DATA_VAULT__/${{ secrets.DATA_VAULT }}/g'' {} \;
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__DB_URL__/${{ secrets.DB_URL }}/g'' {} \;
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__LOG_LEVEL__/${{ secrets.LOG_LEVEL }}/g'' {} \;

      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__SSL__/${{ secrets.SSL }}/g'' {} \;
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__GOOGLE_ARTIFACT_URL__/${{ secrets.GOOGLE_ARTIFACT_URL }}/g'' {} \;
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__GOOGLE_ARTIFACT_REPO__/${{ secrets.GOOGLE_ARTIFACT_REPO }}/g'' {} \;
      - name: "Replace secrets"
        run: find .deploy/deployment.yaml -type f -exec sed  -i ''s/__GOOGLE_PROJECT_ID__/${{ secrets.GOOGLE_PROJECT_ID }}/g'' {} \;

      - name: "Deploy to GKE"
        run: kubectl apply -f .deploy/deployment.yaml
