name: Vault Service Release Docker Workflow

on: push

permissions:
  contents: write
  packages: write

jobs:
  publish-docker:
      name: Publish Docker Image (linux/amd64)
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        
        - name: Set Latest Tag
          run: echo "LATEST_RELEASE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.19
        
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          id: buildx
          with:
            version: latest
        
        - name: Docker Login
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Prepare Docker Metadata
          id: docker-build
          uses: docker/metadata-action@v4
          with:
            images: ghcr.io/${{ github.repository}}
            flavor: |
              latest=auto
            tags: |
              type=semver,pattern={{version}},value=${{ env.LATEST_RELEASE_TAG }}
            labels: |
              org.opencontainers.image.vendor="Hypermine Limited"
        
        - name: Build and push image
          uses: docker/build-push-action@v3
          with:
            context: .
            platforms: linux/amd64
            push: true
            tags: ${{ steps.docker-build.outputs.tags }}
            labels: ${{ steps.docker-build.outputs.labels }}
